name: .NET (build pull request)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET SDK.
      uses: Elskom/setup-latest-dotnet@main
    - name: Restore, Build, and Pack
      uses: Elskom/build-dotnet@main
