name: .NET (build)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET SDK.
      uses: Elskom/setup-latest-dotnet@main
    - name: Restore, Build, and Pack
      uses: Elskom/build-dotnet@main
